name: bus_connect
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_form_builder: ^10.2.0
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0
  go_router: ^17.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^9.0.4

flutter:

  uses-material-design: true
